### ISSUE TITLE
Is this for Authentication only or also for Authorisation?

### ISSUE THREAD

**Issue by VinceW** [bigpresh/Dancer-Plugin-Auth-Extensible#30]
First, tnx for the module. Nice work.

I noticed in the description of the module this module is an: "Authentication framework for Dancer-based web applications"

Currently the module provides more functionality then Authentication alone. It also provides some functionality in the Authorisation spectrum (for instance user_has_role). 

Is this combination intended?

One of the reasons for my question is because I would like to see more authorisation functionality (such as: can_user('Edit this form) etc, but currently I am in doubt where to put this functionality. 

As seen from an architectural point of view there is a difference between Authentication and Authorisation (see also: http://en.wikipedia.org/wiki/AAA_protocol).

This module could be extended with this extra functionality (willing to contribute to it) but isn't this going to be cluttered up to much?

**Comment by bigpresh** [comment]
As I see it, the roles implementation is clear and simple; I don't really see the value of an additional abstraction above that particularly - but I suppose I can see the value of a simple "Could the user execute $method $role" feature, if that's desired.

So - if I implemented a keyword that checks if a user can access a given route with a given method, e.g. `user_can_access_route( DELETE => '/user/:user_id' )`, would that be useful?

That way, the route definition could allow various roles to access it, and you don't need to care which roles the user has if all you want to know is "do they have one of the roles that gives them permission to execute that route?".

**Comment by bigpresh** [comment]
I've raised #56 for the implementation of a `user_can_access_route()` keyword, so I'm going to close this ticket now.  (Sorry it sat for so long!)
