### ISSUE TITLE
Add a note about encrypting passwords to the POD

### ISSUE THREAD

**Issue by MagnusEnger** [bigpresh/Dancer-Plugin-Auth-Extensible#34]
Hi! Thanks for a very useful module - and I just figured out it is even more useful than I thought... ;-) 

I tought I had it all figured out when I got as far as generating passwords like this:

```
my $csh = Crypt::SaltedHash->new();
$csh->add( $plain_text_password );
my $hashed_password = $csh->generate;
```

Then someone complained that this was only providing relatively insecure SHA-1 hashing. After some digging and som friendly advice on IRC (thanks racke!) it turns out that Crypt::SaltedHash can use lots of different algorithms, like e.g.:

```
my $csh = Crypt::SaltedHash->new( 'algorithm' => 'SHA-512' );
```

Since this might be non-obvious to n00bs like me, and has security implications, could it be worth while to point this out in the documentation for the module?

**Comment by bigpresh** [comment]
I've made the `bin/generate-crypted-password` utility script default to SHA-512 to generate more securely-crypted passwords, and added a brief note in the docs suggesting choosing a secure algo.

Sorry this sat undealt-with for so long!
