### ISSUE TITLE
Dancer2

### ISSUE THREAD

**Issue by jacqueslareau** [bigpresh/Dancer-Plugin-Auth-Extensible#36]
I really like this plugin. Will this be ported to Dancer2?

**Comment by bigpresh** [comment]
@racke, now D2 plugins are overhauled and stabilised, do you think there's any chance of merging the D2 stuff back into this version so we'd have one definitive DPAE plugin that works in both Dancer versions, or do you think they're too far diverged at this point?

**Comment by bigpresh** [comment]
I still wonder if there's any potential to merge the two versions back together, but I rather suspect that, at this point, it would be a LOT of work to pull it off.
