### ISSUE TITLE
A possible way to implement your TODO about auto detecting password hashed-ness

### ISSUE THREAD

**Issue by msouth** [bigpresh/Dancer-Plugin-Auth-Extensible#41]
See comment on 

https://github.com/bigpresh/Dancer-Plugin-Auth-Extensible/commit/e21f71903f3ae6d819b4d9ba6b4aa21fcd0cbd97

I think you could use this looks_like_crypt function :http://search.cpan.org/~sharyanto/Crypt-Password-Util-0.09/lib/Crypt/Password/Util.pm#looks_like_crypt($str)_=>_BOOL to make a smart guess about whether a password is encrypted or not (possibly for the 'auto' option you described).

**Comment by hvoers** [comment]
This can be closed. See my comment on e21f719.
