### ISSUE TITLE
LDAP provider is missing in CPAN distribution of DPAE

### ISSUE THREAD

**Issue by mestia** [bigpresh/Dancer-Plugin-Auth-Extensible#48]
JFYI, the LDAP provider is not present on CPAN:
https://metacpan.org/release/Dancer-Plugin-Auth-Extensible
Thank you, 
Alex

**Comment by bigpresh** [comment]
Firstly - eep, sorry this sat unanswered for so long.  That's rubbish of me.  I'm working on responding to all GH issues more quickly, and getting notifications/reminders in place so I can't miss stuff for so long.

As for the issue - I've removed the LDAP provdier from the DPAE core dist; I've spun it out into its own GitHub repo: https://github.com/bigpresh/Dancer-Plugin-Auth-Extensible-Provider-LDAP

I plan to get it on CPAN soon.  However, as I don't currently use LDAP, I'd welcome any contributors who want to help maintain it!
