### ISSUE TITLE
feature request? optimization of logged_in_user() 

### ISSUE THREAD

**Issue by joshrabinowitz** [bigpresh/Dancer-Plugin-Auth-Extensible#49]
See https://github.com/bigpresh/Dancer-Plugin-SimpleCRUD/issues/67#issuecomment-242406968 .

**Comment by joshrabinowitz** [comment]
fixed in https://github.com/bigpresh/Dancer-Plugin-Auth-Extensible/pull/51

**Comment by bigpresh** [comment]
Right, I re-implemented my first stab at this, so that it applies equally to all providers, not just the Database provider, and this work has just hit CPAN in 1.00.
